server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///springboot
    username: root
    password: 123456
